sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_COVERAGE=true
    - php: 7.3
    - php: 7.4

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then composer require --no-update php-coveralls/php-coveralls ; fi

install:
  - travis_retry composer update --no-interaction --prefer-source $COMPOSER_OPTS

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/php-coveralls ; fi
